//{
//    "success": true,
//    "data": {
//        "current_page": 1,
//        "data": [
//        {
//        "id": 810,
//        "ticket_number": 77594,
//        "client_id": 7,
//        "campaign_id": 9,
//        "order_details_id": 137,
//        "is_valid": "Yes",
//        "early_bird": "No",
//        "created_at": "2019-09-30 10:36:11",
//        "updated_at": "2019-09-30 10:36:11",
//        "deleted_at": null,
//        "client_text": "mahmoud bakr",
//        "campaign": {
//        "id": 9,
//        "product_id": 10,
//        "prize_id": 20,
//        "early_bird_setting": 10,
//        "total_num_of_sells": 400,
//        "status": "Closing",
//        "published": 1,
//        "featured": 1,
//        "image": "images/campaigns/Push-on-bitbucket.png",
//        "created_at": "2019-09-26 12:54:34",
//        "updated_at": "2019-10-07 15:43:46",
//        "deleted_at": null,
//        "sold": "159",
//        "product_text": "cash",
//        "prize_text": "test bakr bakr",
//        "published_text": "Yes",
//        "featured_text": "Yes",
//        "product": {
//        "id": 10,
//        "name_en": "cash",
//        "name_ar": "عربى",
//        "description_en": "<div>\r\n<div>\"C:/wamp/cacert.pem\"</div>\r\n</div>",
//        "description_ar": "<div>\r\n<div>\"C:/wamp/cacert.pem\"</div>\r\n</div>",
//        "category_id": 2,
//        "quantity": 55,
//        "image": "images/products/Cash-icon.png",
//        "points": 55,
//        "published": 1,
//        "featured": 1,
//        "created_at": "2019-09-23 06:01:38",
//        "updated_at": "2019-09-23 06:01:38",
//        "deleted_at": null,
//        "name": "cash",
//        "category_text": "category11",
//        "published_text": "Yes",
//        "featured_text": "Yes",
//        "category": {
//        "id": 2,
//        "name_en": "category11",
//        "name_ar": "cat2",
//        "description_en": "<p>ww</p>",
//        "description_ar": "<p>ww</p>",
//        "type_id": 1,
//        "image": "images/categories/ERROR.PNG",
//        "mobile_icon": "images/categories/service.PNG",
//        "published": 1,
//        "created_at": "2019-09-15 06:42:22",
//        "updated_at": "2019-10-10 16:49:37",
//        "deleted_at": null,
//        "name": "category11",
//        "published_text": "Yes",
//        "type_text": "product",
//        "type": {
//        "id": 1,
//        "name_en": "product",
//        "name_ar": "منتج",
//        "created_at": "2019-09-15 09:23:57",
//        "updated_at": "2019-09-15 09:23:57",
//        "deleted_at": null
//        }
//        }
//        },
//        "prize": {
//        "id": 20,
//        "name_en": "test bakr bakr",
//        "name_ar": "test bakr bakr",
//        "description_en": "<p>test bakr bakr</p>",
//        "description_ar": "<p>test bakr bakr</p>",
//        "category_id": 1,
//        "image": "images/prizes/69722967_484987855631383_748649822310891520_n.jpg",
//        "published": 1,
//        "created_at": "2019-09-17 12:47:04",
//        "updated_at": "2019-09-17 12:47:04",
//        "deleted_at": null,
//        "name": "cash",
//        "published_text": "Yes",
//        "category_text": "category1",
//        "category": {
//        "id": 1,
//        "name_en": "category1",
//        "name_ar": "قسم1",
//        "description_en": "desc1",
//        "description_ar": "وصف1",
//        "type_id": 2,
//        "image": "images/sliders/service.PNG",
//        "mobile_icon": "images/sliders/69874994_2366894683526350_6720412014692270080_n.jpg",
//        "published": 1,
//        "created_at": "2019-09-15 06:40:28",
//        "updated_at": "2019-09-15 07:10:12",
//        "deleted_at": null,
//        "name": "category11",
//        "published_text": "Yes",
//        "type_text": "prize",
//        "type": {
//        "id": 2,
//        "name_en": "prize",
//        "name_ar": "جائزه",
//        "created_at": "2019-09-15 09:24:14",
//        "updated_at": "2019-09-15 09:24:14",
//        "deleted_at": null
//        }
//        }
//        }
//        },
//        "client": {
//        "id": 7,
//        "first_name": "mahmoud",
//        "last_name": "bakr",
//        "gender": null,
//        "email": "fathikhgvjhhj@gmail.com",
//        "phone_number": "01145033268",
//        "code": "ZhKq53yznlcV",
//        "is_verify": 0,
//        "country_id": 2,
//        "nationality_id": null,
//        "token": null,
//        "level_id": 4,
//        "purchase_points": 10667091,
//        "referal_points": null,
//        "total_points": 10667043,
//        "total_spent": 48,
//        "image": null,
//        "rate": null,
//        "friend_id": 6,
//        "leveled_at": "2019-10-14 17:35:55",
//        "created_at": "2019-09-26 05:43:27",
//        "updated_at": "2019-10-14 17:35:55",
//        "deleted_at": null,
//        "country_text": "Albania",
//        "level_text": "Gold",
//        "country": {
//        "id": 2,
//        "name_en": "Albania",
//        "name_ar": "ألبانيا",
//        "code": "AL",
//        "is_shippable": "Yes",
//        "accept_cache": "Yes",
//        "key_country": "",
//        "image": "images/countries/Flag-wave-250.png",
//        "created_at": null,
//        "updated_at": null,
//        "deleted_at": null,
//        "name": "Albania"
//        },
//        "level": {
//        "id": 4,
//        "name_en": "Gold",
//        "name_ar": "ذهبى",
//        "limit_points": 7500,
//        "created_at": "2019-09-30 12:30:49",
//        "updated_at": "2019-09-30 12:30:49",
//        "deleted_at": null
//        }
//        }
//        },
//        {
//        "id": 809,
//        "ticket_number": 98318,
//        "client_id": 7,
//        "campaign_id": 9,
//        "order_details_id": 137,
//        "is_valid": "Yes",
//        "early_bird": "No",
//        "created_at": "2019-09-30 10:36:11",
//        "updated_at": "2019-09-30 10:36:11",
//        "deleted_at": null,
//        "client_text": "mahmoud bakr",
//        "campaign": {
//        "id": 9,
//        "product_id": 10,
//        "prize_id": 20,
//        "early_bird_setting": 10,
//        "total_num_of_sells": 400,
//        "status": "Closing",
//        "published": 1,
//        "featured": 1,
//        "image": "images/campaigns/Push-on-bitbucket.png",
//        "created_at": "2019-09-26 12:54:34",
//        "updated_at": "2019-10-07 15:43:46",
//        "deleted_at": null,
//        "sold": "159",
//        "product_text": "cash",
//        "prize_text": "test bakr bakr",
//        "published_text": "Yes",
//        "featured_text": "Yes",
//        "product": {
//        "id": 10,
//        "name_en": "cash",
//        "name_ar": "عربى",
//        "description_en": "<div>\r\n<div>\"C:/wamp/cacert.pem\"</div>\r\n</div>",
//        "description_ar": "<div>\r\n<div>\"C:/wamp/cacert.pem\"</div>\r\n</div>",
//        "category_id": 2,
//        "quantity": 55,
//        "image": "images/products/Cash-icon.png",
//        "points": 55,
//        "published": 1,
//        "featured": 1,
//        "created_at": "2019-09-23 06:01:38",
//        "updated_at": "2019-09-23 06:01:38",
//        "deleted_at": null,
//        "name": "cash",
//        "category_text": "category11",
//        "published_text": "Yes",
//        "featured_text": "Yes",
//        "category": {
//        "id": 2,
//        "name_en": "category11",
//        "name_ar": "cat2",
//        "description_en": "<p>ww</p>",
//        "description_ar": "<p>ww</p>",
//        "type_id": 1,
//        "image": "images/categories/ERROR.PNG",
//        "mobile_icon": "images/categories/service.PNG",
//        "published": 1,
//        "created_at": "2019-09-15 06:42:22",
//        "updated_at": "2019-10-10 16:49:37",
//        "deleted_at": null,
//        "name": "category11",
//        "published_text": "Yes",
//        "type_text": "product",
//        "type": {
//        "id": 1,
//        "name_en": "product",
//        "name_ar": "منتج",
//        "created_at": "2019-09-15 09:23:57",
//        "updated_at": "2019-09-15 09:23:57",
//        "deleted_at": null
//        }
//        }
//        },
//        "prize": {
//        "id": 20,
//        "name_en": "test bakr bakr",
//        "name_ar": "test bakr bakr",
//        "description_en": "<p>test bakr bakr</p>",
//        "description_ar": "<p>test bakr bakr</p>",
//        "category_id": 1,
//        "image": "images/prizes/69722967_484987855631383_748649822310891520_n.jpg",
//        "published": 1,
//        "created_at": "2019-09-17 12:47:04",
//        "updated_at": "2019-09-17 12:47:04",
//        "deleted_at": null,
//        "name": "cash",
//        "published_text": "Yes",
//        "category_text": "category1",
//        "category": {
//        "id": 1,
//        "name_en": "category1",
//        "name_ar": "قسم1",
//        "description_en": "desc1",
//        "description_ar": "وصف1",
//        "type_id": 2,
//        "image": "images/sliders/service.PNG",
//        "mobile_icon": "images/sliders/69874994_2366894683526350_6720412014692270080_n.jpg",
//        "published": 1,
//        "created_at": "2019-09-15 06:40:28",
//        "updated_at": "2019-09-15 07:10:12",
//        "deleted_at": null,
//        "name": "category11",
//        "published_text": "Yes",
//        "type_text": "prize",
//        "type": {
//        "id": 2,
//        "name_en": "prize",
//        "name_ar": "جائزه",
//        "created_at": "2019-09-15 09:24:14",
//        "updated_at": "2019-09-15 09:24:14",
//        "deleted_at": null
//        }
//        }
//        }
//        },
//        "client": {
//        "id": 7,
//        "first_name": "mahmoud",
//        "last_name": "bakr",
//        "gender": null,
//        "email": "fathikhgvjhhj@gmail.com",
//        "phone_number": "01145033268",
//        "code": "ZhKq53yznlcV",
//        "is_verify": 0,
//        "country_id": 2,
//        "nationality_id": null,
//        "token": null,
//        "level_id": 4,
//        "purchase_points": 10667091,
//        "referal_points": null,
//        "total_points": 10667043,
//        "total_spent": 48,
//        "image": null,
//        "rate": null,
//        "friend_id": 6,
//        "leveled_at": "2019-10-14 17:35:55",
//        "created_at": "2019-09-26 05:43:27",
//        "updated_at": "2019-10-14 17:35:55",
//        "deleted_at": null,
//        "country_text": "Albania",
//        "level_text": "Gold",
//        "country": {
//        "id": 2,
//        "name_en": "Albania",
//        "name_ar": "ألبانيا",
//        "code": "AL",
//        "is_shippable": "Yes",
//        "accept_cache": "Yes",
//        "key_country": "",
//        "image": "images/countries/Flag-wave-250.png",
//        "created_at": null,
//        "updated_at": null,
//        "deleted_at": null,
//        "name": "Albania"
//        },
//        "level": {
//        "id": 4,
//        "name_en": "Gold",
//        "name_ar": "ذهبى",
//        "limit_points": 7500,
//        "created_at": "2019-09-30 12:30:49",
//        "updated_at": "2019-09-30 12:30:49",
//        "deleted_at": null
//        }
//        }
//        },
//        {
//        "id": 808,
//        "ticket_number": 67215,
//        "client_id": 7,
//        "campaign_id": 9,
//        "order_details_id": 137,
//        "is_valid": "Yes",
//        "early_bird": "No",
//        "created_at": "2019-09-30 10:36:11",
//        "updated_at": "2019-09-30 10:36:11",
//        "deleted_at": null,
//        "client_text": "mahmoud bakr",
//        "campaign": {
//        "id": 9,
//        "product_id": 10,
//        "prize_id": 20,
//        "early_bird_setting": 10,
//        "total_num_of_sells": 400,
//        "status": "Closing",
//        "published": 1,
//        "featured": 1,
//        "image": "images/campaigns/Push-on-bitbucket.png",
//        "created_at": "2019-09-26 12:54:34",
//        "updated_at": "2019-10-07 15:43:46",
//        "deleted_at": null,
//        "sold": "159",
//        "product_text": "cash",
//        "prize_text": "test bakr bakr",
//        "published_text": "Yes",
//        "featured_text": "Yes",
//        "product": {
//        "id": 10,
//        "name_en": "cash",
//        "name_ar": "عربى",
//        "description_en": "<div>\r\n<div>\"C:/wamp/cacert.pem\"</div>\r\n</div>",
//        "description_ar": "<div>\r\n<div>\"C:/wamp/cacert.pem\"</div>\r\n</div>",
//        "category_id": 2,
//        "quantity": 55,
//        "image": "images/products/Cash-icon.png",
//        "points": 55,
//        "published": 1,
//        "featured": 1,
//        "created_at": "2019-09-23 06:01:38",
//        "updated_at": "2019-09-23 06:01:38",
//        "deleted_at": null,
//        "name": "cash",
//        "category_text": "category11",
//        "published_text": "Yes",
//        "featured_text": "Yes",
//        "category": {
//        "id": 2,
//        "name_en": "category11",
//        "name_ar": "cat2",
//        "description_en": "<p>ww</p>",
//        "description_ar": "<p>ww</p>",
//        "type_id": 1,
//        "image": "images/categories/ERROR.PNG",
//        "mobile_icon": "images/categories/service.PNG",
//        "published": 1,
//        "created_at": "2019-09-15 06:42:22",
//        "updated_at": "2019-10-10 16:49:37",
//        "deleted_at": null,
//        "name": "category11",
//        "published_text": "Yes",
//        "type_text": "product",
//        "type": {
//        "id": 1,
//        "name_en": "product",
//        "name_ar": "منتج",
//        "created_at": "2019-09-15 09:23:57",
//        "updated_at": "2019-09-15 09:23:57",
//        "deleted_at": null
//        }
//        }
//        },
//        "prize": {
//        "id": 20,
//        "name_en": "test bakr bakr",
//        "name_ar": "test bakr bakr",
//        "description_en": "<p>test bakr bakr</p>",
//        "description_ar": "<p>test bakr bakr</p>",
//        "category_id": 1,
//        "image": "images/prizes/69722967_484987855631383_748649822310891520_n.jpg",
//        "published": 1,
//        "created_at": "2019-09-17 12:47:04",
//        "updated_at": "2019-09-17 12:47:04",
//        "deleted_at": null,
//        "name": "cash",
//        "published_text": "Yes",
//        "category_text": "category1",
//        "category": {
//        "id": 1,
//        "name_en": "category1",
//        "name_ar": "قسم1",
//        "description_en": "desc1",
//        "description_ar": "وصف1",
//        "type_id": 2,
//        "image": "images/sliders/service.PNG",
//        "mobile_icon": "images/sliders/69874994_2366894683526350_6720412014692270080_n.jpg",
//        "published": 1,
//        "created_at": "2019-09-15 06:40:28",
//        "updated_at": "2019-09-15 07:10:12",
//        "deleted_at": null,
//        "name": "category11",
//        "published_text": "Yes",
//        "type_text": "prize",
//        "type": {
//        "id": 2,
//        "name_en": "prize",
//        "name_ar": "جائزه",
//        "created_at": "2019-09-15 09:24:14",
//        "updated_at": "2019-09-15 09:24:14",
//        "deleted_at": null
//        }
//        }
//        }
//        },
//        "client": {
//        "id": 7,
//        "first_name": "mahmoud",
//        "last_name": "bakr",
//        "gender": null,
//        "email": "fathikhgvjhhj@gmail.com",
//        "phone_number": "01145033268",
//        "code": "ZhKq53yznlcV",
//        "is_verify": 0,
//        "country_id": 2,
//        "nationality_id": null,
//        "token": null,
//        "level_id": 4,
//        "purchase_points": 10667091,
//        "referal_points": null,
//        "total_points": 10667043,
//        "total_spent": 48,
//        "image": null,
//        "rate": null,
//        "friend_id": 6,
//        "leveled_at": "2019-10-14 17:35:55",
//        "created_at": "2019-09-26 05:43:27",
//        "updated_at": "2019-10-14 17:35:55",
//        "deleted_at": null,
//        "country_text": "Albania",
//        "level_text": "Gold",
//        "country": {
//        "id": 2,
//        "name_en": "Albania",
//        "name_ar": "ألبانيا",
//        "code": "AL",
//        "is_shippable": "Yes",
//        "accept_cache": "Yes",
//        "key_country": "",
//        "image": "images/countries/Flag-wave-250.png",
//        "created_at": null,
//        "updated_at": null,
//        "deleted_at": null,
//        "name": "Albania"
//        },
//        "level": {
//        "id": 4,
//        "name_en": "Gold",
//        "name_ar": "ذهبى",
//        "limit_points": 7500,
//        "created_at": "2019-09-30 12:30:49",
//        "updated_at": "2019-09-30 12:30:49",
//        "deleted_at": null
//        }
//        }
//        },
//        {
//        "id": 807,
//        "ticket_number": 73377,
//        "client_id": 7,
//        "campaign_id": 9,
//        "order_details_id": 137,
//        "is_valid": "Yes",
//        "early_bird": "No",
//        "created_at": "2019-09-30 10:36:11",
//        "updated_at": "2019-09-30 10:36:11",
//        "deleted_at": null,
//        "client_text": "mahmoud bakr",
//        "campaign": {
//        "id": 9,
//        "product_id": 10,
//        "prize_id": 20,
//        "early_bird_setting": 10,
//        "total_num_of_sells": 400,
//        "status": "Closing",
//        "published": 1,
//        "featured": 1,
//        "image": "images/campaigns/Push-on-bitbucket.png",
//        "created_at": "2019-09-26 12:54:34",
//        "updated_at": "2019-10-07 15:43:46",
//        "deleted_at": null,
//        "sold": "159",
//        "product_text": "cash",
//        "prize_text": "test bakr bakr",
//        "published_text": "Yes",
//        "featured_text": "Yes",
//        "product": {
//        "id": 10,
//        "name_en": "cash",
//        "name_ar": "عربى",
//        "description_en": "<div>\r\n<div>\"C:/wamp/cacert.pem\"</div>\r\n</div>",
//        "description_ar": "<div>\r\n<div>\"C:/wamp/cacert.pem\"</div>\r\n</div>",
//        "category_id": 2,
//        "quantity": 55,
//        "image": "images/products/Cash-icon.png",
//        "points": 55,
//        "published": 1,
//        "featured": 1,
//        "created_at": "2019-09-23 06:01:38",
//        "updated_at": "2019-09-23 06:01:38",
//        "deleted_at": null,
//        "name": "cash",
//        "category_text": "category11",
//        "published_text": "Yes",
//        "featured_text": "Yes",
//        "category": {
//        "id": 2,
//        "name_en": "category11",
//        "name_ar": "cat2",
//        "description_en": "<p>ww</p>",
//        "description_ar": "<p>ww</p>",
//        "type_id": 1,
//        "image": "images/categories/ERROR.PNG",
//        "mobile_icon": "images/categories/service.PNG",
//        "published": 1,
//        "created_at": "2019-09-15 06:42:22",
//        "updated_at": "2019-10-10 16:49:37",
//        "deleted_at": null,
//        "name": "category11",
//        "published_text": "Yes",
//        "type_text": "product",
//        "type": {
//        "id": 1,
//        "name_en": "product",
//        "name_ar": "منتج",
//        "created_at": "2019-09-15 09:23:57",
//        "updated_at": "2019-09-15 09:23:57",
//        "deleted_at": null
//        }
//        }
//        },
//        "prize": {
//        "id": 20,
//        "name_en": "test bakr bakr",
//        "name_ar": "test bakr bakr",
//        "description_en": "<p>test bakr bakr</p>",
//        "description_ar": "<p>test bakr bakr</p>",
//        "category_id": 1,
//        "image": "images/prizes/69722967_484987855631383_748649822310891520_n.jpg",
//        "published": 1,
//        "created_at": "2019-09-17 12:47:04",
//        "updated_at": "2019-09-17 12:47:04",
//        "deleted_at": null,
//        "name": "cash",
//        "published_text": "Yes",
//        "category_text": "category1",
//        "category": {
//        "id": 1,
//        "name_en": "category1",
//        "name_ar": "قسم1",
//        "description_en": "desc1",
//        "description_ar": "وصف1",
//        "type_id": 2,
//        "image": "images/sliders/service.PNG",
//        "mobile_icon": "images/sliders/69874994_2366894683526350_6720412014692270080_n.jpg",
//        "published": 1,
//        "created_at": "2019-09-15 06:40:28",
//        "updated_at": "2019-09-15 07:10:12",
//        "deleted_at": null,
//        "name": "category11",
//        "published_text": "Yes",
//        "type_text": "prize",
//        "type": {
//        "id": 2,
//        "name_en": "prize",
//        "name_ar": "جائزه",
//        "created_at": "2019-09-15 09:24:14",
//        "updated_at": "2019-09-15 09:24:14",
//        "deleted_at": null
//        }
//        }
//        }
//        },
//        "client": {
//        "id": 7,
//        "first_name": "mahmoud",
//        "last_name": "bakr",
//        "gender": null,
//        "email": "fathikhgvjhhj@gmail.com",
//        "phone_number": "01145033268",
//        "code": "ZhKq53yznlcV",
//        "is_verify": 0,
//        "country_id": 2,
//        "nationality_id": null,
//        "token": null,
//        "level_id": 4,
//        "purchase_points": 10667091,
//        "referal_points": null,
//        "total_points": 10667043,
//        "total_spent": 48,
//        "image": null,
//        "rate": null,
//        "friend_id": 6,
//        "leveled_at": "2019-10-14 17:35:55",
//        "created_at": "2019-09-26 05:43:27",
//        "updated_at": "2019-10-14 17:35:55",
//        "deleted_at": null,
//        "country_text": "Albania",
//        "level_text": "Gold",
//        "country": {
//        "id": 2,
//        "name_en": "Albania",
//        "name_ar": "ألبانيا",
//        "code": "AL",
//        "is_shippable": "Yes",
//        "accept_cache": "Yes",
//        "key_country": "",
//        "image": "images/countries/Flag-wave-250.png",
//        "created_at": null,
//        "updated_at": null,
//        "deleted_at": null,
//        "name": "Albania"
//        },
//        "level": {
//        "id": 4,
//        "name_en": "Gold",
//        "name_ar": "ذهبى",
//        "limit_points": 7500,
//        "created_at": "2019-09-30 12:30:49",
//        "updated_at": "2019-09-30 12:30:49",
//        "deleted_at": null
//        }
//        }
//        },
//        {
//        "id": 806,
//        "ticket_number": 19054,
//        "client_id": 7,
//        "campaign_id": 9,
//        "order_details_id": 137,
//        "is_valid": "Yes",
//        "early_bird": "No",
//        "created_at": "2019-09-30 10:36:11",
//        "updated_at": "2019-09-30 10:36:11",
//        "deleted_at": null,
//        "client_text": "mahmoud bakr",
//        "campaign": {
//        "id": 9,
//        "product_id": 10,
//        "prize_id": 20,
//        "early_bird_setting": 10,
//        "total_num_of_sells": 400,
//        "status": "Closing",
//        "published": 1,
//        "featured": 1,
//        "image": "images/campaigns/Push-on-bitbucket.png",
//        "created_at": "2019-09-26 12:54:34",
//        "updated_at": "2019-10-07 15:43:46",
//        "deleted_at": null,
//        "sold": "159",
//        "product_text": "cash",
//        "prize_text": "test bakr bakr",
//        "published_text": "Yes",
//        "featured_text": "Yes",
//        "product": {
//        "id": 10,
//        "name_en": "cash",
//        "name_ar": "عربى",
//        "description_en": "<div>\r\n<div>\"C:/wamp/cacert.pem\"</div>\r\n</div>",
//        "description_ar": "<div>\r\n<div>\"C:/wamp/cacert.pem\"</div>\r\n</div>",
//        "category_id": 2,
//        "quantity": 55,
//        "image": "images/products/Cash-icon.png",
//        "points": 55,
//        "published": 1,
//        "featured": 1,
//        "created_at": "2019-09-23 06:01:38",
//        "updated_at": "2019-09-23 06:01:38",
//        "deleted_at": null,
//        "name": "cash",
//        "category_text": "category11",
//        "published_text": "Yes",
//        "featured_text": "Yes",
//        "category": {
//        "id": 2,
//        "name_en": "category11",
//        "name_ar": "cat2",
//        "description_en": "<p>ww</p>",
//        "description_ar": "<p>ww</p>",
//        "type_id": 1,
//        "image": "images/categories/ERROR.PNG",
//        "mobile_icon": "images/categories/service.PNG",
//        "published": 1,
//        "created_at": "2019-09-15 06:42:22",
//        "updated_at": "2019-10-10 16:49:37",
//        "deleted_at": null,
//        "name": "category11",
//        "published_text": "Yes",
//        "type_text": "product",
//        "type": {
//        "id": 1,
//        "name_en": "product",
//        "name_ar": "منتج",
//        "created_at": "2019-09-15 09:23:57",
//        "updated_at": "2019-09-15 09:23:57",
//        "deleted_at": null
//        }
//        }
//        },
//        "prize": {
//        "id": 20,
//        "name_en": "test bakr bakr",
//        "name_ar": "test bakr bakr",
//        "description_en": "<p>test bakr bakr</p>",
//        "description_ar": "<p>test bakr bakr</p>",
//        "category_id": 1,
//        "image": "images/prizes/69722967_484987855631383_748649822310891520_n.jpg",
//        "published": 1,
//        "created_at": "2019-09-17 12:47:04",
//        "updated_at": "2019-09-17 12:47:04",
//        "deleted_at": null,
//        "name": "cash",
//        "published_text": "Yes",
//        "category_text": "category1",
//        "category": {
//        "id": 1,
//        "name_en": "category1",
//        "name_ar": "قسم1",
//        "description_en": "desc1",
//        "description_ar": "وصف1",
//        "type_id": 2,
//        "image": "images/sliders/service.PNG",
//        "mobile_icon": "images/sliders/69874994_2366894683526350_6720412014692270080_n.jpg",
//        "published": 1,
//        "created_at": "2019-09-15 06:40:28",
//        "updated_at": "2019-09-15 07:10:12",
//        "deleted_at": null,
//        "name": "category11",
//        "published_text": "Yes",
//        "type_text": "prize",
//        "type": {
//        "id": 2,
//        "name_en": "prize",
//        "name_ar": "جائزه",
//        "created_at": "2019-09-15 09:24:14",
//        "updated_at": "2019-09-15 09:24:14",
//        "deleted_at": null
//        }
//        }
//        }
//        },
//        "client": {
//        "id": 7,
//        "first_name": "mahmoud",
//        "last_name": "bakr",
//        "gender": null,
//        "email": "fathikhgvjhhj@gmail.com",
//        "phone_number": "01145033268",
//        "code": "ZhKq53yznlcV",
//        "is_verify": 0,
//        "country_id": 2,
//        "nationality_id": null,
//        "token": null,
//        "level_id": 4,
//        "purchase_points": 10667091,
//        "referal_points": null,
//        "total_points": 10667043,
//        "total_spent": 48,
//        "image": null,
//        "rate": null,
//        "friend_id": 6,
//        "leveled_at": "2019-10-14 17:35:55",
//        "created_at": "2019-09-26 05:43:27",
//        "updated_at": "2019-10-14 17:35:55",
//        "deleted_at": null,
//        "country_text": "Albania",
//        "level_text": "Gold",
//        "country": {
//        "id": 2,
//        "name_en": "Albania",
//        "name_ar": "ألبانيا",
//        "code": "AL",
//        "is_shippable": "Yes",
//        "accept_cache": "Yes",
//        "key_country": "",
//        "image": "images/countries/Flag-wave-250.png",
//        "created_at": null,
//        "updated_at": null,
//        "deleted_at": null,
//        "name": "Albania"
//        },
//        "level": {
//        "id": 4,
//        "name_en": "Gold",
//        "name_ar": "ذهبى",
//        "limit_points": 7500,
//        "created_at": "2019-09-30 12:30:49",
//        "updated_at": "2019-09-30 12:30:49",
//        "deleted_at": null
//        }
//        }
//        }
//        ],
//        "first_page_url": "http://deal4deal.app/deal4deal_backend/public/api/tickets?page=1",
//        "from": 1,
//        "last_page": 37,
//        "last_page_url": "http://deal4deal.app/deal4deal_backend/public/api/tickets?page=37",
//        "next_page_url": "http://deal4deal.app/deal4deal_backend/public/api/tickets?page=2",
//        "path": "http://deal4deal.app/deal4deal_backend/public/api/tickets",
//        "per_page": 5,
//        "prev_page_url": null,
//        "to": 5,
//        "total": 183
//    },
//    "message": "Tickets retrieved successfully",
//    "status_code": 200
//}
